version: "0"
services: 
  postgres:
    image: postgres
    container_name: DB
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=db
    volumes:
      - ./db:/docker-entrypoint-initdb.d